(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["vendors~_"],{

/***/ "./node_modules/@sveltejs/svelte-scroller/src/Scroller.html":
/*!******************************************************************!*\
  !*** ./node_modules/@sveltejs/svelte-scroller/src/Scroller.html ***!
  \******************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/shared.js */ "./node_modules/svelte/shared.js");
/* node_modules/@sveltejs/svelte-scroller/src/Scroller.html generated by Svelte v2.7.2 */


const scrollers = [];

if (typeof window !== 'undefined') {
	window.addEventListener('scroll', () => {
		scrollers.forEach(scroller => {
			scroller.handleScroll();
		});
	});
}

let manager;

if (typeof IntersectionObserver !== 'undefined') {
	const map = new Map();

	const observer = new IntersectionObserver((entries, observer) => {
		entries.forEach(entry => {
			const scroller = map.get(entry.target);
			const index = scrollers.indexOf(scroller);

			if (entry.isIntersecting) {
				if (index === -1) scrollers.push(scroller);
			} else {
				if (index !== -1) scrollers.splice(index, 1);
			}
		});
	}, {
		rootMargin: '400px 0px'
	});

	manager = {
		add: scroller => {
			const { outer } = scroller.refs;
			const { top, bottom } = outer.getBoundingClientRect();

			if (top < window.innerHeight && bottom > 0) scrollers.push(scroller);

			map.set(outer, scroller);
			observer.observe(outer);
		},

		remove: scroller => {
			const index = scrollers.indexOf(scroller);
			if (index !== -1) scrollers.splice(index, 1);

			map.delete(scroller.refs.outer);
			observer.unobserve(scroller.refs.outer);
		}
	};
} else {
	manager = {
		add: scroller => {
			scrollers.push(scroller);
		},

		remove: scroller => {
			const index = scrollers.indexOf(scroller);
			if (index !== -1) scrollers.splice(index, 1);
		}
	};
}

function top_px({ top, wh }) {
	return Math.round(top * wh);
}

function bottom_px({ bottom, wh }) {
	return Math.round(bottom * wh);
}

function threshold_px({ threshold, wh }) {
	return Math.round(threshold * wh);
}

function style({ fixed, offset_top, bottom_px, top_px, width, height, inverted }) {
	return `
		position: ${fixed ? 'fixed' : 'absolute'};
		top: 0;
		transform: translate(0, ${offset_top}px);
		width: ${width}px;
		z-index: ${inverted ? 3 : 1};
	`;
};

function data() {
	return {
		top: 0,
		bottom: 1,
		threshold: 0.5,

		count: 0,
		index: 0,
		offset: 0,
		progress: 0,

		query: 'section'
	};
};

var methods = {
	handleScroll() {
		const { top_px, bottom_px, threshold_px, parallax } = this.get();

		// determine fix state
		const foreground = this.refs.foreground.getBoundingClientRect();
		const background = this.refs.background.getBoundingClientRect();

		// only update while the foreground is visible
		// (only affects browsers without IntersectionObserver)
		if (foreground.top > window.innerHeight || foreground.bottom < 0) return;

		const foreground_height = foreground.bottom - foreground.top;
		const background_height = background.bottom - background.top;

		const available_space = bottom_px - top_px;
		const p = (top_px - foreground.top) / (foreground_height - available_space);

		const { sections } = this;

		let offset_top;
		let fixed;
		let index;
		let offset;

		if (p <= 0) {
			offset_top = 0;
			fixed = false;
			offset = 0;
			index = -1;
		} else if (p >= 1) {
			offset_top = parallax
				? (foreground_height - background_height)
				: (foreground_height - available_space);
			fixed = false;
			offset = 1;
			index = sections.length - 1;
		} else {
			offset_top = parallax ?
				Math.round(top_px - p * (background_height - available_space)) :
				top_px;
			fixed = true;
		}

		for (index = 0; index < this.sections.length; index += 1) {
			const section = this.sections[index];
			const { top } = section.getBoundingClientRect();

			const next = this.sections[index + 1];
			const bottom = next ? next.getBoundingClientRect().top : this.refs.foreground.getBoundingClientRect().bottom;

			if (bottom >= threshold_px) {
				offset = (threshold_px - top) / (bottom - top);
				break;
			}
		}

		this.set({
			progress: p,
			index,
			offset,

			offset_top,
			fixed
		});
	},

	handleResize() {
		const { left, right } = this.refs.outer.getBoundingClientRect();

		const bg = this.refs.background.getBoundingClientRect();
		const fg = this.refs.foreground.getBoundingClientRect();

		this.set({
			width: right - left,
			foreground_height: fg.bottom - fg.top,
			background_height: bg.bottom - bg.top,
			left
		});
	}
};

function oncreate() {
	this.sections = this.refs.foreground.querySelectorAll(this.get().query);
	this.set({ count: this.sections.length });

	this.handleResize();
	this.handleScroll();

	this.on('state', ({ changed }) => {
		if (changed.top || changed.threshold || changed.bottom || changed.parallax) {
			this.handleScroll();
		}
	});

	manager.add(this);
};

function ondestroy() {
	manager.remove(this);
};

const file = "node_modules/sveltejs/svelte-scroller/src/Scroller.html";

function add_css() {
	var style = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("style");
	style.id = 'svelte-7ydq3l-style';
	style.textContent = ".svelte-ref-outer.svelte-7ydq3l{position:relative}.svelte-ref-background.svelte-7ydq3l{position:relative;width:100%}.svelte-ref-foreground.svelte-7ydq3l{position:relative;z-index:2}.svelte-ref-foreground.svelte-7ydq3l::after{content:' ';display:block;clear:both}.background-container.svelte-7ydq3l{position:absolute;width:100%;pointer-events:none;will-change:transform}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2Nyb2xsZXIuaHRtbCIsInNvdXJjZXMiOlsiU2Nyb2xsZXIuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3ZlbHRlOndpbmRvdyBiaW5kOmlubmVySGVpZ2h0PXdoIG9uOnJlc2l6ZT0naGFuZGxlUmVzaXplKCknLz5cblxuPGRpdiByZWY6b3V0ZXI+XG5cdDxkaXYgY2xhc3M9J2JhY2tncm91bmQtY29udGFpbmVyJyB7c3R5bGV9PlxuXHRcdDxkaXYgcmVmOmJhY2tncm91bmQ+XG5cdFx0XHQ8c2xvdCBuYW1lPSdiYWNrZ3JvdW5kJz48L3Nsb3Q+XG5cdFx0PC9kaXY+XG5cdDwvZGl2PlxuXG5cdDxkaXYgcmVmOmZvcmVncm91bmQ+XG5cdFx0PHNsb3QgbmFtZT0nZm9yZWdyb3VuZCc+PC9zbG90PlxuXHQ8L2Rpdj5cbjwvZGl2PlxuXG48c3R5bGU+XG5cdHJlZjpvdXRlciB7XG5cdFx0cG9zaXRpb246IHJlbGF0aXZlO1xuXHR9XG5cblx0cmVmOmJhY2tncm91bmQge1xuXHRcdHBvc2l0aW9uOiByZWxhdGl2ZTtcblx0XHR3aWR0aDogMTAwJTtcblx0fVxuXG5cdHJlZjpmb3JlZ3JvdW5kIHtcblx0XHRwb3NpdGlvbjogcmVsYXRpdmU7XG5cdFx0ei1pbmRleDogMjtcblx0fVxuXG5cdHJlZjpmb3JlZ3JvdW5kOjphZnRlciB7XG5cdFx0Y29udGVudDogJyAnO1xuXHRcdGRpc3BsYXk6IGJsb2NrO1xuXHRcdGNsZWFyOiBib3RoO1xuXHR9XG5cblx0LmJhY2tncm91bmQtY29udGFpbmVyIHtcblx0XHRwb3NpdGlvbjogYWJzb2x1dGU7XG5cdFx0d2lkdGg6IDEwMCU7XG5cdFx0cG9pbnRlci1ldmVudHM6IG5vbmU7XG5cdFx0LyogaGVpZ2h0OiAxMDAlOyAqL1xuXG5cdFx0LyogaW4gdGhlb3J5IHRoaXMgaGVscHMgcHJldmVudCBqdW1waW5nICovXG5cdFx0d2lsbC1jaGFuZ2U6IHRyYW5zZm9ybTtcblx0XHQvKiAtd2Via2l0LXRyYW5zZm9ybTogdHJhbnNsYXRlM2QoMCwgMCwgMCk7XG5cdFx0LW1vei10cmFuc2Zvcm06IHRyYW5zbGF0ZTNkKDAsIDAsIDApO1xuXHRcdHRyYW5zZm9ybTogdHJhbnNsYXRlM2QoMCwgMCwgMCk7ICovXG5cdH1cbjwvc3R5bGU+XG5cbjxzY3JpcHQ+XG5cdGNvbnN0IHNjcm9sbGVycyA9IFtdO1xuXG5cdGlmICh0eXBlb2Ygd2luZG93ICE9PSAndW5kZWZpbmVkJykge1xuXHRcdHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdzY3JvbGwnLCAoKSA9PiB7XG5cdFx0XHRzY3JvbGxlcnMuZm9yRWFjaChzY3JvbGxlciA9PiB7XG5cdFx0XHRcdHNjcm9sbGVyLmhhbmRsZVNjcm9sbCgpO1xuXHRcdFx0fSk7XG5cdFx0fSk7XG5cdH1cblxuXHRsZXQgbWFuYWdlcjtcblxuXHRpZiAodHlwZW9mIEludGVyc2VjdGlvbk9ic2VydmVyICE9PSAndW5kZWZpbmVkJykge1xuXHRcdGNvbnN0IG1hcCA9IG5ldyBNYXAoKTtcblxuXHRcdGNvbnN0IG9ic2VydmVyID0gbmV3IEludGVyc2VjdGlvbk9ic2VydmVyKChlbnRyaWVzLCBvYnNlcnZlcikgPT4ge1xuXHRcdFx0ZW50cmllcy5mb3JFYWNoKGVudHJ5ID0+IHtcblx0XHRcdFx0Y29uc3Qgc2Nyb2xsZXIgPSBtYXAuZ2V0KGVudHJ5LnRhcmdldCk7XG5cdFx0XHRcdGNvbnN0IGluZGV4ID0gc2Nyb2xsZXJzLmluZGV4T2Yoc2Nyb2xsZXIpO1xuXG5cdFx0XHRcdGlmIChlbnRyeS5pc0ludGVyc2VjdGluZykge1xuXHRcdFx0XHRcdGlmIChpbmRleCA9PT0gLTEpIHNjcm9sbGVycy5wdXNoKHNjcm9sbGVyKTtcblx0XHRcdFx0fSBlbHNlIHtcblx0XHRcdFx0XHRpZiAoaW5kZXggIT09IC0xKSBzY3JvbGxlcnMuc3BsaWNlKGluZGV4LCAxKTtcblx0XHRcdFx0fVxuXHRcdFx0fSk7XG5cdFx0fSwge1xuXHRcdFx0cm9vdE1hcmdpbjogJzQwMHB4IDBweCdcblx0XHR9KTtcblxuXHRcdG1hbmFnZXIgPSB7XG5cdFx0XHRhZGQ6IHNjcm9sbGVyID0+IHtcblx0XHRcdFx0Y29uc3QgeyBvdXRlciB9ID0gc2Nyb2xsZXIucmVmcztcblx0XHRcdFx0Y29uc3QgeyB0b3AsIGJvdHRvbSB9ID0gb3V0ZXIuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7XG5cblx0XHRcdFx0aWYgKHRvcCA8IHdpbmRvdy5pbm5lckhlaWdodCAmJiBib3R0b20gPiAwKSBzY3JvbGxlcnMucHVzaChzY3JvbGxlcik7XG5cblx0XHRcdFx0bWFwLnNldChvdXRlciwgc2Nyb2xsZXIpO1xuXHRcdFx0XHRvYnNlcnZlci5vYnNlcnZlKG91dGVyKTtcblx0XHRcdH0sXG5cblx0XHRcdHJlbW92ZTogc2Nyb2xsZXIgPT4ge1xuXHRcdFx0XHRjb25zdCBpbmRleCA9IHNjcm9sbGVycy5pbmRleE9mKHNjcm9sbGVyKTtcblx0XHRcdFx0aWYgKGluZGV4ICE9PSAtMSkgc2Nyb2xsZXJzLnNwbGljZShpbmRleCwgMSk7XG5cblx0XHRcdFx0bWFwLmRlbGV0ZShzY3JvbGxlci5yZWZzLm91dGVyKTtcblx0XHRcdFx0b2JzZXJ2ZXIudW5vYnNlcnZlKHNjcm9sbGVyLnJlZnMub3V0ZXIpO1xuXHRcdFx0fVxuXHRcdH07XG5cdH0gZWxzZSB7XG5cdFx0bWFuYWdlciA9IHtcblx0XHRcdGFkZDogc2Nyb2xsZXIgPT4ge1xuXHRcdFx0XHRzY3JvbGxlcnMucHVzaChzY3JvbGxlcik7XG5cdFx0XHR9LFxuXG5cdFx0XHRyZW1vdmU6IHNjcm9sbGVyID0+IHtcblx0XHRcdFx0Y29uc3QgaW5kZXggPSBzY3JvbGxlcnMuaW5kZXhPZihzY3JvbGxlcik7XG5cdFx0XHRcdGlmIChpbmRleCAhPT0gLTEpIHNjcm9sbGVycy5zcGxpY2UoaW5kZXgsIDEpO1xuXHRcdFx0fVxuXHRcdH07XG5cdH1cblxuXHRleHBvcnQgZGVmYXVsdCB7XG5cdFx0ZGF0YSgpIHtcblx0XHRcdHJldHVybiB7XG5cdFx0XHRcdHRvcDogMCxcblx0XHRcdFx0Ym90dG9tOiAxLFxuXHRcdFx0XHR0aHJlc2hvbGQ6IDAuNSxcblxuXHRcdFx0XHRjb3VudDogMCxcblx0XHRcdFx0aW5kZXg6IDAsXG5cdFx0XHRcdG9mZnNldDogMCxcblx0XHRcdFx0cHJvZ3Jlc3M6IDAsXG5cblx0XHRcdFx0cXVlcnk6ICdzZWN0aW9uJ1xuXHRcdFx0fTtcblx0XHR9LFxuXG5cdFx0Y29tcHV0ZWQ6IHtcblx0XHRcdHRvcF9weDogKHsgdG9wLCB3aCB9KSA9PiBNYXRoLnJvdW5kKHRvcCAqIHdoKSxcblx0XHRcdGJvdHRvbV9weDogKHsgYm90dG9tLCB3aCB9KSA9PiBNYXRoLnJvdW5kKGJvdHRvbSAqIHdoKSxcblx0XHRcdHRocmVzaG9sZF9weDogKHsgdGhyZXNob2xkLCB3aCB9KSA9PiBNYXRoLnJvdW5kKHRocmVzaG9sZCAqIHdoKSxcblxuXHRcdFx0c3R5bGUoeyBmaXhlZCwgb2Zmc2V0X3RvcCwgYm90dG9tX3B4LCB0b3BfcHgsIHdpZHRoLCBoZWlnaHQsIGludmVydGVkIH0pIHtcblx0XHRcdFx0cmV0dXJuIGBcblx0XHRcdFx0XHRwb3NpdGlvbjogJHtmaXhlZCA/ICdmaXhlZCcgOiAnYWJzb2x1dGUnfTtcblx0XHRcdFx0XHR0b3A6IDA7XG5cdFx0XHRcdFx0dHJhbnNmb3JtOiB0cmFuc2xhdGUoMCwgJHtvZmZzZXRfdG9wfXB4KTtcblx0XHRcdFx0XHR3aWR0aDogJHt3aWR0aH1weDtcblx0XHRcdFx0XHR6LWluZGV4OiAke2ludmVydGVkID8gMyA6IDF9O1xuXHRcdFx0XHRgO1xuXHRcdFx0fVxuXHRcdH0sXG5cblx0XHRvbmNyZWF0ZSgpIHtcblx0XHRcdHRoaXMuc2VjdGlvbnMgPSB0aGlzLnJlZnMuZm9yZWdyb3VuZC5xdWVyeVNlbGVjdG9yQWxsKHRoaXMuZ2V0KCkucXVlcnkpO1xuXHRcdFx0dGhpcy5zZXQoeyBjb3VudDogdGhpcy5zZWN0aW9ucy5sZW5ndGggfSk7XG5cblx0XHRcdHRoaXMuaGFuZGxlUmVzaXplKCk7XG5cdFx0XHR0aGlzLmhhbmRsZVNjcm9sbCgpO1xuXG5cdFx0XHR0aGlzLm9uKCdzdGF0ZScsICh7IGNoYW5nZWQgfSkgPT4ge1xuXHRcdFx0XHRpZiAoY2hhbmdlZC50b3AgfHwgY2hhbmdlZC50aHJlc2hvbGQgfHwgY2hhbmdlZC5ib3R0b20gfHwgY2hhbmdlZC5wYXJhbGxheCkge1xuXHRcdFx0XHRcdHRoaXMuaGFuZGxlU2Nyb2xsKCk7XG5cdFx0XHRcdH1cblx0XHRcdH0pO1xuXG5cdFx0XHRtYW5hZ2VyLmFkZCh0aGlzKTtcblx0XHR9LFxuXG5cdFx0b25kZXN0cm95KCkge1xuXHRcdFx0bWFuYWdlci5yZW1vdmUodGhpcyk7XG5cdFx0fSxcblxuXHRcdG1ldGhvZHM6IHtcblx0XHRcdGhhbmRsZVNjcm9sbCgpIHtcblx0XHRcdFx0Y29uc3QgeyB0b3BfcHgsIGJvdHRvbV9weCwgdGhyZXNob2xkX3B4LCBwYXJhbGxheCB9ID0gdGhpcy5nZXQoKTtcblxuXHRcdFx0XHQvLyBkZXRlcm1pbmUgZml4IHN0YXRlXG5cdFx0XHRcdGNvbnN0IGZvcmVncm91bmQgPSB0aGlzLnJlZnMuZm9yZWdyb3VuZC5nZXRCb3VuZGluZ0NsaWVudFJlY3QoKTtcblx0XHRcdFx0Y29uc3QgYmFja2dyb3VuZCA9IHRoaXMucmVmcy5iYWNrZ3JvdW5kLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuXG5cdFx0XHRcdC8vIG9ubHkgdXBkYXRlIHdoaWxlIHRoZSBmb3JlZ3JvdW5kIGlzIHZpc2libGVcblx0XHRcdFx0Ly8gKG9ubHkgYWZmZWN0cyBicm93c2VycyB3aXRob3V0IEludGVyc2VjdGlvbk9ic2VydmVyKVxuXHRcdFx0XHRpZiAoZm9yZWdyb3VuZC50b3AgPiB3aW5kb3cuaW5uZXJIZWlnaHQgfHwgZm9yZWdyb3VuZC5ib3R0b20gPCAwKSByZXR1cm47XG5cblx0XHRcdFx0Y29uc3QgZm9yZWdyb3VuZF9oZWlnaHQgPSBmb3JlZ3JvdW5kLmJvdHRvbSAtIGZvcmVncm91bmQudG9wO1xuXHRcdFx0XHRjb25zdCBiYWNrZ3JvdW5kX2hlaWdodCA9IGJhY2tncm91bmQuYm90dG9tIC0gYmFja2dyb3VuZC50b3A7XG5cblx0XHRcdFx0Y29uc3QgYXZhaWxhYmxlX3NwYWNlID0gYm90dG9tX3B4IC0gdG9wX3B4O1xuXHRcdFx0XHRjb25zdCBwID0gKHRvcF9weCAtIGZvcmVncm91bmQudG9wKSAvIChmb3JlZ3JvdW5kX2hlaWdodCAtIGF2YWlsYWJsZV9zcGFjZSk7XG5cblx0XHRcdFx0Y29uc3QgeyBzZWN0aW9ucyB9ID0gdGhpcztcblxuXHRcdFx0XHRsZXQgb2Zmc2V0X3RvcDtcblx0XHRcdFx0bGV0IGZpeGVkO1xuXHRcdFx0XHRsZXQgaW5kZXg7XG5cdFx0XHRcdGxldCBvZmZzZXQ7XG5cblx0XHRcdFx0aWYgKHAgPD0gMCkge1xuXHRcdFx0XHRcdG9mZnNldF90b3AgPSAwO1xuXHRcdFx0XHRcdGZpeGVkID0gZmFsc2U7XG5cdFx0XHRcdFx0b2Zmc2V0ID0gMDtcblx0XHRcdFx0XHRpbmRleCA9IC0xO1xuXHRcdFx0XHR9IGVsc2UgaWYgKHAgPj0gMSkge1xuXHRcdFx0XHRcdG9mZnNldF90b3AgPSBwYXJhbGxheFxuXHRcdFx0XHRcdFx0PyAoZm9yZWdyb3VuZF9oZWlnaHQgLSBiYWNrZ3JvdW5kX2hlaWdodClcblx0XHRcdFx0XHRcdDogKGZvcmVncm91bmRfaGVpZ2h0IC0gYXZhaWxhYmxlX3NwYWNlKTtcblx0XHRcdFx0XHRmaXhlZCA9IGZhbHNlO1xuXHRcdFx0XHRcdG9mZnNldCA9IDE7XG5cdFx0XHRcdFx0aW5kZXggPSBzZWN0aW9ucy5sZW5ndGggLSAxO1xuXHRcdFx0XHR9IGVsc2Uge1xuXHRcdFx0XHRcdG9mZnNldF90b3AgPSBwYXJhbGxheCA/XG5cdFx0XHRcdFx0XHRNYXRoLnJvdW5kKHRvcF9weCAtIHAgKiAoYmFja2dyb3VuZF9oZWlnaHQgLSBhdmFpbGFibGVfc3BhY2UpKSA6XG5cdFx0XHRcdFx0XHR0b3BfcHg7XG5cdFx0XHRcdFx0Zml4ZWQgPSB0cnVlO1xuXHRcdFx0XHR9XG5cblx0XHRcdFx0Zm9yIChpbmRleCA9IDA7IGluZGV4IDwgdGhpcy5zZWN0aW9ucy5sZW5ndGg7IGluZGV4ICs9IDEpIHtcblx0XHRcdFx0XHRjb25zdCBzZWN0aW9uID0gdGhpcy5zZWN0aW9uc1tpbmRleF07XG5cdFx0XHRcdFx0Y29uc3QgeyB0b3AgfSA9IHNlY3Rpb24uZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7XG5cblx0XHRcdFx0XHRjb25zdCBuZXh0ID0gdGhpcy5zZWN0aW9uc1tpbmRleCArIDFdO1xuXHRcdFx0XHRcdGNvbnN0IGJvdHRvbSA9IG5leHQgPyBuZXh0LmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpLnRvcCA6IHRoaXMucmVmcy5mb3JlZ3JvdW5kLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpLmJvdHRvbTtcblxuXHRcdFx0XHRcdGlmIChib3R0b20gPj0gdGhyZXNob2xkX3B4KSB7XG5cdFx0XHRcdFx0XHRvZmZzZXQgPSAodGhyZXNob2xkX3B4IC0gdG9wKSAvIChib3R0b20gLSB0b3ApO1xuXHRcdFx0XHRcdFx0YnJlYWs7XG5cdFx0XHRcdFx0fVxuXHRcdFx0XHR9XG5cblx0XHRcdFx0dGhpcy5zZXQoe1xuXHRcdFx0XHRcdHByb2dyZXNzOiBwLFxuXHRcdFx0XHRcdGluZGV4LFxuXHRcdFx0XHRcdG9mZnNldCxcblxuXHRcdFx0XHRcdG9mZnNldF90b3AsXG5cdFx0XHRcdFx0Zml4ZWRcblx0XHRcdFx0fSk7XG5cdFx0XHR9LFxuXG5cdFx0XHRoYW5kbGVSZXNpemUoKSB7XG5cdFx0XHRcdGNvbnN0IHsgbGVmdCwgcmlnaHQgfSA9IHRoaXMucmVmcy5vdXRlci5nZXRCb3VuZGluZ0NsaWVudFJlY3QoKTtcblxuXHRcdFx0XHRjb25zdCBiZyA9IHRoaXMucmVmcy5iYWNrZ3JvdW5kLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuXHRcdFx0XHRjb25zdCBmZyA9IHRoaXMucmVmcy5mb3JlZ3JvdW5kLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuXG5cdFx0XHRcdHRoaXMuc2V0KHtcblx0XHRcdFx0XHR3aWR0aDogcmlnaHQgLSBsZWZ0LFxuXHRcdFx0XHRcdGZvcmVncm91bmRfaGVpZ2h0OiBmZy5ib3R0b20gLSBmZy50b3AsXG5cdFx0XHRcdFx0YmFja2dyb3VuZF9oZWlnaHQ6IGJnLmJvdHRvbSAtIGJnLnRvcCxcblx0XHRcdFx0XHRsZWZ0XG5cdFx0XHRcdH0pO1xuXHRcdFx0fVxuXHRcdH1cblx0fTtcbjwvc2NyaXB0PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWVDLCtCQUFVLENBQUMsQUFDVixRQUFRLENBQUUsUUFBUSxBQUNuQixDQUFDLEFBRUQsb0NBQWUsQ0FBQyxBQUNmLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEtBQUssQ0FBRSxJQUFJLEFBQ1osQ0FBQyxBQUVELG9DQUFlLENBQUMsQUFDZixRQUFRLENBQUUsUUFBUSxDQUNsQixPQUFPLENBQUUsQ0FBQyxBQUNYLENBQUMsQUFFRCxvQ0FBYyxPQUFPLEFBQUMsQ0FBQyxBQUN0QixPQUFPLENBQUUsR0FBRyxDQUNaLE9BQU8sQ0FBRSxLQUFLLENBQ2QsS0FBSyxDQUFFLElBQUksQUFDWixDQUFDLEFBRUQscUJBQXFCLGNBQUMsQ0FBQyxBQUN0QixRQUFRLENBQUUsUUFBUSxDQUNsQixLQUFLLENBQUUsSUFBSSxDQUNYLGNBQWMsQ0FBRSxJQUFJLENBSXBCLFdBQVcsQ0FBRSxTQUFTLEFBSXZCLENBQUMifQ== */";
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(style, document.head);
}

function create_main_fragment(component, ctx) {
	var div, div_1, div_2, slot_content_background = component._slotted.background, text_2, div_3, slot_content_foreground = component._slotted.foreground;

	function onwindowresize(event) {
		component.handleResize();;
	}
	window.addEventListener("resize", onwindowresize);

	function onwindowresize_1(event) {
		component._updatingReadonlyProperty = true;

		component.set({
			wh: this.innerHeight
		});

		component._updatingReadonlyProperty = false;
	}
	window.addEventListener("resize", onwindowresize_1);

	return {
		c: function create() {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createText"])("\n\n\t");
			div_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["createElement"])("div");
			this.h()
		},

		l: function claim(nodes) {
			div = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(nodes, "DIV", { class: true }, false);
			var div_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			div_1 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true, style: true }, false);
			var div_1_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_1);

			div_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_1_nodes, "DIV", { class: true }, false);
			var div_2_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_2);

			div_2_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_1_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			text_2 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimText"])(div_nodes, "\n\n\t");

			div_3 = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["claimElement"])(div_nodes, "DIV", { class: true }, false);
			var div_3_nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(div_3);

			div_3_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			div_nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
			this.h();
		},

		h: function hydrate() {
			div_2.className = "svelte-7ydq3l svelte-ref-background";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_2, file, 4, 2, 127);
			div_1.className = "background-container svelte-7ydq3l";
			div_1.style.cssText = ctx.style;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_1, file, 3, 1, 82);
			div_3.className = "svelte-7ydq3l svelte-ref-foreground";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div_3, file, 9, 1, 202);
			div.className = "svelte-7ydq3l svelte-ref-outer";
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["addLoc"])(div, file, 2, 0, 65);
		},

		m: function mount(target, anchor) {
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["insertNode"])(div, target, anchor);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_1, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_2, div_1);

			if (slot_content_background) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(slot_content_background, div_2);
			}

			component.refs.background = div_2;
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(text_2, div);
			Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(div_3, div);

			if (slot_content_foreground) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["appendNode"])(slot_content_foreground, div_3);
			}

			component.refs.foreground = div_3;
			component.refs.outer = div;
		},

		p: function update(changed, ctx) {
			if (changed.style) {
				div_1.style.cssText = ctx.style;
			}
		},

		d: function destroy(detach) {
			window.removeEventListener("resize", onwindowresize);

			window.removeEventListener("resize", onwindowresize_1);

			if (detach) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"])(div);
			}

			if (slot_content_background) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["reinsertChildren"])(div_2, slot_content_background);
			}

			if (component.refs.background === div_2) component.refs.background = null;

			if (slot_content_foreground) {
				Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["reinsertChildren"])(div_3, slot_content_foreground);
			}

			if (component.refs.foreground === div_3) component.refs.foreground = null;
			if (component.refs.outer === div) component.refs.outer = null;
		}
	};
}

function Scroller(options) {
	this._debugName = '<Scroller>';
	if (!options || (!options.target && !options.root)) throw new Error("'target' is a required option");
	Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options);
	this.refs = {};
	this._state = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(data(), options.data);
	this._state.wh = window.innerHeight;
	this._recompute({ top: 1, wh: 1, bottom: 1, threshold: 1, fixed: 1, offset_top: 1, bottom_px: 1, top_px: 1, width: 1, height: 1, inverted: 1 }, this._state);
	if (!('top' in this._state)) console.warn("<Scroller> was created without expected data property 'top'");
	if (!('wh' in this._state)) console.warn("<Scroller> was created without expected data property 'wh'");
	if (!('bottom' in this._state)) console.warn("<Scroller> was created without expected data property 'bottom'");
	if (!('threshold' in this._state)) console.warn("<Scroller> was created without expected data property 'threshold'");
	if (!('fixed' in this._state)) console.warn("<Scroller> was created without expected data property 'fixed'");
	if (!('offset_top' in this._state)) console.warn("<Scroller> was created without expected data property 'offset_top'");


	if (!('width' in this._state)) console.warn("<Scroller> was created without expected data property 'width'");
	if (!('height' in this._state)) console.warn("<Scroller> was created without expected data property 'height'");
	if (!('inverted' in this._state)) console.warn("<Scroller> was created without expected data property 'inverted'");
	this._intro = true;

	this._handlers.destroy = [ondestroy];

	this._slotted = options.slots || {};

	if (!document.getElementById("svelte-7ydq3l-style")) add_css();

	if (!options.root) {
		this._oncreate = [];
	}

	this.slots = {};

	this._fragment = create_main_fragment(this, this._state);

	this.root._oncreate.push(() => {
		oncreate.call(this);
		this.fire("update", { changed: Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assignTrue"])({}, this._state), current: this._state });
	});

	if (options.target) {
		var nodes = Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["children"])(options.target);
		options.hydrate ? this._fragment.l(nodes) : this._fragment.c();
		nodes.forEach(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["detachNode"]);
		this._mount(options.target, options.anchor);

		Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["callAll"])(this._oncreate);
	}
}

Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Scroller.prototype, svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["protoDev"]);
Object(svelte_shared_js__WEBPACK_IMPORTED_MODULE_0__["assign"])(Scroller.prototype, methods);

Scroller.prototype._checkReadOnly = function _checkReadOnly(newState) {
	if ('wh' in newState && !this._updatingReadonlyProperty) throw new Error("<Scroller>: Cannot set read-only property 'wh'");
	if ('top_px' in newState && !this._updatingReadonlyProperty) throw new Error("<Scroller>: Cannot set read-only property 'top_px'");
	if ('bottom_px' in newState && !this._updatingReadonlyProperty) throw new Error("<Scroller>: Cannot set read-only property 'bottom_px'");
	if ('threshold_px' in newState && !this._updatingReadonlyProperty) throw new Error("<Scroller>: Cannot set read-only property 'threshold_px'");
	if ('style' in newState && !this._updatingReadonlyProperty) throw new Error("<Scroller>: Cannot set read-only property 'style'");
};

Scroller.prototype._recompute = function _recompute(changed, state) {
	if (changed.top || changed.wh) {
		if (this._differs(state.top_px, (state.top_px = top_px(state)))) changed.top_px = true;
	}

	if (changed.bottom || changed.wh) {
		if (this._differs(state.bottom_px, (state.bottom_px = bottom_px(state)))) changed.bottom_px = true;
	}

	if (changed.threshold || changed.wh) {
		if (this._differs(state.threshold_px, (state.threshold_px = threshold_px(state)))) changed.threshold_px = true;
	}

	if (changed.fixed || changed.offset_top || changed.bottom_px || changed.top_px || changed.width || changed.height || changed.inverted) {
		if (this._differs(state.style, (state.style = style(state)))) changed.style = true;
	}
}

if (true) {
	const { configure, register, reload } = __webpack_require__(/*! ./node_modules/svelte-loader/lib/hot-api.js */ "./node_modules/svelte-loader/lib/hot-api.js");

	module.hot.accept();

	if (!module.hot.data) {
		// initial load
		configure({});
		Scroller = register("node_modules/@sveltejs/svelte-scroller/src/Scroller.html", Scroller);
	} else {
		// hot update
		Scroller = reload("node_modules/@sveltejs/svelte-scroller/src/Scroller.html", Scroller);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Scroller);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvQHN2ZWx0ZWpzL3N2ZWx0ZS1zY3JvbGxlci9zcmMvU2Nyb2xsZXIuaHRtbCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7QUFrREMsTUFBTSxTQUFTLEdBQUcsRUFBRSxDQUFDOztBQUVyQixJQUFJLE9BQU8sTUFBTSxLQUFLLFdBQVcsRUFBRTtBQUNuQyxDQUFDLE1BQU0sQ0FBQyxnQkFBZ0IsQ0FBQyxRQUFRLEVBQUUsTUFBTTtBQUN6QyxFQUFFLFNBQVMsQ0FBQyxPQUFPLENBQUMsUUFBUSxJQUFJO0FBQ2hDLEdBQUcsUUFBUSxDQUFDLFlBQVksRUFBRSxDQUFDO0FBQzNCLEdBQUcsQ0FBQyxDQUFDO0FBQ0wsRUFBRSxDQUFDLENBQUM7QUFDSixDQUFDOztBQUVELElBQUksT0FBTyxDQUFDOztBQUVaLElBQUksT0FBTyxvQkFBb0IsS0FBSyxXQUFXLEVBQUU7QUFDakQsQ0FBQyxNQUFNLEdBQUcsR0FBRyxJQUFJLEdBQUcsRUFBRSxDQUFDOztBQUV2QixDQUFDLE1BQU0sUUFBUSxHQUFHLElBQUksb0JBQW9CLENBQUMsQ0FBQyxPQUFPLEVBQUUsUUFBUSxLQUFLO0FBQ2xFLEVBQUUsT0FBTyxDQUFDLE9BQU8sQ0FBQyxLQUFLLElBQUk7QUFDM0IsR0FBRyxNQUFNLFFBQVEsR0FBRyxHQUFHLENBQUMsR0FBRyxDQUFDLEtBQUssQ0FBQyxNQUFNLENBQUMsQ0FBQztBQUMxQyxHQUFHLE1BQU0sS0FBSyxHQUFHLFNBQVMsQ0FBQyxPQUFPLENBQUMsUUFBUSxDQUFDLENBQUM7O0FBRTdDLEdBQUcsSUFBSSxLQUFLLENBQUMsY0FBYyxFQUFFO0FBQzdCLElBQUksSUFBSSxLQUFLLEtBQUssQ0FBQyxDQUFDLEVBQUUsU0FBUyxDQUFDLElBQUksQ0FBQyxRQUFRLENBQUMsQ0FBQztBQUMvQyxJQUFJLE1BQU07QUFDVixJQUFJLElBQUksS0FBSyxLQUFLLENBQUMsQ0FBQyxFQUFFLFNBQVMsQ0FBQyxNQUFNLENBQUMsS0FBSyxFQUFFLENBQUMsQ0FBQyxDQUFDO0FBQ2pELElBQUk7QUFDSixHQUFHLENBQUMsQ0FBQztBQUNMLEVBQUUsRUFBRTtBQUNKLEVBQUUsVUFBVSxFQUFFLFdBQVc7QUFDekIsRUFBRSxDQUFDLENBQUM7O0FBRUosQ0FBQyxPQUFPLEdBQUc7QUFDWCxFQUFFLEdBQUcsRUFBRSxRQUFRLElBQUk7QUFDbkIsR0FBRyxNQUFNLEVBQUUsS0FBSyxFQUFFLEdBQUcsUUFBUSxDQUFDLElBQUksQ0FBQztBQUNuQyxHQUFHLE1BQU0sRUFBRSxHQUFHLEVBQUUsTUFBTSxFQUFFLEdBQUcsS0FBSyxDQUFDLHFCQUFxQixFQUFFLENBQUM7O0FBRXpELEdBQUcsSUFBSSxHQUFHLEdBQUcsTUFBTSxDQUFDLFdBQVcsSUFBSSxNQUFNLEdBQUcsQ0FBQyxFQUFFLFNBQVMsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLENBQUM7O0FBRXhFLEdBQUcsR0FBRyxDQUFDLEdBQUcsQ0FBQyxLQUFLLEVBQUUsUUFBUSxDQUFDLENBQUM7QUFDNUIsR0FBRyxRQUFRLENBQUMsT0FBTyxDQUFDLEtBQUssQ0FBQyxDQUFDO0FBQzNCLEdBQUc7O0FBRUgsRUFBRSxNQUFNLEVBQUUsUUFBUSxJQUFJO0FBQ3RCLEdBQUcsTUFBTSxLQUFLLEdBQUcsU0FBUyxDQUFDLE9BQU8sQ0FBQyxRQUFRLENBQUMsQ0FBQztBQUM3QyxHQUFHLElBQUksS0FBSyxLQUFLLENBQUMsQ0FBQyxFQUFFLFNBQVMsQ0FBQyxNQUFNLENBQUMsS0FBSyxFQUFFLENBQUMsQ0FBQyxDQUFDOztBQUVoRCxHQUFHLEdBQUcsQ0FBQyxNQUFNLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsQ0FBQztBQUNuQyxHQUFHLFFBQVEsQ0FBQyxTQUFTLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsQ0FBQztBQUMzQyxHQUFHO0FBQ0gsRUFBRSxDQUFDO0FBQ0gsQ0FBQyxNQUFNO0FBQ1AsQ0FBQyxPQUFPLEdBQUc7QUFDWCxFQUFFLEdBQUcsRUFBRSxRQUFRLElBQUk7QUFDbkIsR0FBRyxTQUFTLENBQUMsSUFBSSxDQUFDLFFBQVEsQ0FBQyxDQUFDO0FBQzVCLEdBQUc7O0FBRUgsRUFBRSxNQUFNLEVBQUUsUUFBUSxJQUFJO0FBQ3RCLEdBQUcsTUFBTSxLQUFLLEdBQUcsU0FBUyxDQUFDLE9BQU8sQ0FBQyxRQUFRLENBQUMsQ0FBQztBQUM3QyxHQUFHLElBQUksS0FBSyxLQUFLLENBQUMsQ0FBQyxFQUFFLFNBQVMsQ0FBQyxNQUFNLENBQUMsS0FBSyxFQUFFLENBQUMsQ0FBQyxDQUFDO0FBQ2hELEdBQUc7QUFDSCxFQUFFLENBQUM7QUFDSCxDQUFDOztBQUVGLGdCQWlCWSxFQUFFLEdBQUcsRUFBRSxFQUFFLEVBQUU7UUFBSyxJQUFJLENBQUMsS0FBSyxDQUFDLEdBQUcsR0FBRyxFQUFFLENBQUM7OzttQkFDakMsRUFBRSxNQUFNLEVBQUUsRUFBRSxFQUFFO1FBQUssSUFBSSxDQUFDLEtBQUssQ0FBQyxNQUFNLEdBQUcsRUFBRSxDQUFDOzs7c0JBQ3ZDLEVBQUUsU0FBUyxFQUFFLEVBQUUsRUFBRTtRQUFLLElBQUksQ0FBQyxLQUFLLENBQUMsU0FBUyxHQUFHLEVBQUUsQ0FBQzs7O2NBRTFELENBQUMsRUFBRSxLQUFLLEVBQUUsVUFBVSxFQUFFLFNBQVMsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFLE1BQU0sRUFBRSxRQUFRLEVBQUUsRUFBRTtBQUN6RSxDQUFDLE9BQU8sQ0FBQztBQUNULFlBQVksRUFBRSxLQUFLLEdBQUcsT0FBTyxHQUFHLFVBQVUsQ0FBQztBQUMzQztBQUNBLDBCQUEwQixFQUFFLFVBQVUsQ0FBQztBQUN2QyxTQUFTLEVBQUUsS0FBSyxDQUFDO0FBQ2pCLFdBQVcsRUFBRSxRQUFRLEdBQUcsQ0FBQyxHQUFHLENBQUMsQ0FBQztBQUM5QixDQUFDLENBQUMsQ0FBQztBQUNILENBQUM7O2FBNUJFLEdBQUc7QUFDUCxDQUFDLE9BQU87QUFDUixFQUFFLEdBQUcsRUFBRSxDQUFDO0FBQ1IsRUFBRSxNQUFNLEVBQUUsQ0FBQztBQUNYLEVBQUUsU0FBUyxFQUFFLEdBQUc7O0FBRWhCLEVBQUUsS0FBSyxFQUFFLENBQUM7QUFDVixFQUFFLEtBQUssRUFBRSxDQUFDO0FBQ1YsRUFBRSxNQUFNLEVBQUUsQ0FBQztBQUNYLEVBQUUsUUFBUSxFQUFFLENBQUM7O0FBRWIsRUFBRSxLQUFLLEVBQUUsU0FBUztBQUNsQixFQUFFLENBQUM7QUFDSCxDQUFDOztjQXNDUTtBQUNULENBQUMsWUFBWSxHQUFHO0FBQ2hCLEVBQUUsTUFBTSxFQUFFLE1BQU0sRUFBRSxTQUFTLEVBQUUsWUFBWSxFQUFFLFFBQVEsRUFBRSxHQUFHLElBQUksQ0FBQyxHQUFHLEVBQUUsQ0FBQzs7QUFFbkU7QUFDQSxFQUFFLE1BQU0sVUFBVSxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsVUFBVSxDQUFDLHFCQUFxQixFQUFFLENBQUM7QUFDbEUsRUFBRSxNQUFNLFVBQVUsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVUsQ0FBQyxxQkFBcUIsRUFBRSxDQUFDOztBQUVsRTtBQUNBO0FBQ0EsRUFBRSxJQUFJLFVBQVUsQ0FBQyxHQUFHLEdBQUcsTUFBTSxDQUFDLFdBQVcsSUFBSSxVQUFVLENBQUMsTUFBTSxHQUFHLENBQUMsRUFBRSxPQUFPOztBQUUzRSxFQUFFLE1BQU0saUJBQWlCLEdBQUcsVUFBVSxDQUFDLE1BQU0sR0FBRyxVQUFVLENBQUMsR0FBRyxDQUFDO0FBQy9ELEVBQUUsTUFBTSxpQkFBaUIsR0FBRyxVQUFVLENBQUMsTUFBTSxHQUFHLFVBQVUsQ0FBQyxHQUFHLENBQUM7O0FBRS9ELEVBQUUsTUFBTSxlQUFlLEdBQUcsU0FBUyxHQUFHLE1BQU0sQ0FBQztBQUM3QyxFQUFFLE1BQU0sQ0FBQyxHQUFHLENBQUMsTUFBTSxHQUFHLFVBQVUsQ0FBQyxHQUFHLEtBQUssaUJBQWlCLEdBQUcsZUFBZSxDQUFDLENBQUM7O0FBRTlFLEVBQUUsTUFBTSxFQUFFLFFBQVEsRUFBRSxHQUFHLElBQUksQ0FBQzs7QUFFNUIsRUFBRSxJQUFJLFVBQVUsQ0FBQztBQUNqQixFQUFFLElBQUksS0FBSyxDQUFDO0FBQ1osRUFBRSxJQUFJLEtBQUssQ0FBQztBQUNaLEVBQUUsSUFBSSxNQUFNLENBQUM7O0FBRWIsRUFBRSxJQUFJLENBQUMsSUFBSSxDQUFDLEVBQUU7QUFDZCxHQUFHLFVBQVUsR0FBRyxDQUFDLENBQUM7QUFDbEIsR0FBRyxLQUFLLEdBQUcsS0FBSyxDQUFDO0FBQ2pCLEdBQUcsTUFBTSxHQUFHLENBQUMsQ0FBQztBQUNkLEdBQUcsS0FBSyxHQUFHLENBQUMsQ0FBQyxDQUFDO0FBQ2QsR0FBRyxNQUFNLElBQUksQ0FBQyxJQUFJLENBQUMsRUFBRTtBQUNyQixHQUFHLFVBQVUsR0FBRyxRQUFRO0FBQ3hCLE9BQU8saUJBQWlCLEdBQUcsaUJBQWlCO0FBQzVDLE9BQU8saUJBQWlCLEdBQUcsZUFBZSxDQUFDLENBQUM7QUFDNUMsR0FBRyxLQUFLLEdBQUcsS0FBSyxDQUFDO0FBQ2pCLEdBQUcsTUFBTSxHQUFHLENBQUMsQ0FBQztBQUNkLEdBQUcsS0FBSyxHQUFHLFFBQVEsQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDO0FBQy9CLEdBQUcsTUFBTTtBQUNULEdBQUcsVUFBVSxHQUFHLFFBQVE7QUFDeEIsSUFBSSxJQUFJLENBQUMsS0FBSyxDQUFDLE1BQU0sR0FBRyxDQUFDLElBQUksaUJBQWlCLEdBQUcsZUFBZSxDQUFDLENBQUM7QUFDbEUsSUFBSSxNQUFNLENBQUM7QUFDWCxHQUFHLEtBQUssR0FBRyxJQUFJLENBQUM7QUFDaEIsR0FBRzs7QUFFSCxFQUFFLEtBQUssS0FBSyxHQUFHLENBQUMsRUFBRSxLQUFLLEdBQUcsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsS0FBSyxJQUFJLENBQUMsRUFBRTtBQUM1RCxHQUFHLE1BQU0sT0FBTyxHQUFHLElBQUksQ0FBQyxRQUFRLENBQUMsS0FBSyxDQUFDLENBQUM7QUFDeEMsR0FBRyxNQUFNLEVBQUUsR0FBRyxFQUFFLEdBQUcsT0FBTyxDQUFDLHFCQUFxQixFQUFFLENBQUM7O0FBRW5ELEdBQUcsTUFBTSxJQUFJLEdBQUcsSUFBSSxDQUFDLFFBQVEsQ0FBQyxLQUFLLEdBQUcsQ0FBQyxDQUFDLENBQUM7QUFDekMsR0FBRyxNQUFNLE1BQU0sR0FBRyxJQUFJLEdBQUcsSUFBSSxDQUFDLHFCQUFxQixFQUFFLENBQUMsR0FBRyxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsVUFBVSxDQUFDLHFCQUFxQixFQUFFLENBQUMsTUFBTSxDQUFDOztBQUVoSCxHQUFHLElBQUksTUFBTSxJQUFJLFlBQVksRUFBRTtBQUMvQixJQUFJLE1BQU0sR0FBRyxDQUFDLFlBQVksR0FBRyxHQUFHLEtBQUssTUFBTSxHQUFHLEdBQUcsQ0FBQyxDQUFDO0FBQ25ELElBQUksTUFBTTtBQUNWLElBQUk7QUFDSixHQUFHOztBQUVILEVBQUUsSUFBSSxDQUFDLEdBQUcsQ0FBQztBQUNYLEdBQUcsUUFBUSxFQUFFLENBQUM7QUFDZCxHQUFHLEtBQUs7QUFDUixHQUFHLE1BQU07O0FBRVQsR0FBRyxVQUFVO0FBQ2IsR0FBRyxLQUFLO0FBQ1IsR0FBRyxDQUFDLENBQUM7QUFDTCxFQUFFOztBQUVGLENBQUMsWUFBWSxHQUFHO0FBQ2hCLEVBQUUsTUFBTSxFQUFFLElBQUksRUFBRSxLQUFLLEVBQUUsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxxQkFBcUIsRUFBRSxDQUFDOztBQUVsRSxFQUFFLE1BQU0sRUFBRSxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsVUFBVSxDQUFDLHFCQUFxQixFQUFFLENBQUM7QUFDMUQsRUFBRSxNQUFNLEVBQUUsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLFVBQVUsQ0FBQyxxQkFBcUIsRUFBRSxDQUFDOztBQUUxRCxFQUFFLElBQUksQ0FBQyxHQUFHLENBQUM7QUFDWCxHQUFHLEtBQUssRUFBRSxLQUFLLEdBQUcsSUFBSTtBQUN0QixHQUFHLGlCQUFpQixFQUFFLEVBQUUsQ0FBQyxNQUFNLEdBQUcsRUFBRSxDQUFDLEdBQUc7QUFDeEMsR0FBRyxpQkFBaUIsRUFBRSxFQUFFLENBQUMsTUFBTSxHQUFHLEVBQUUsQ0FBQyxHQUFHO0FBQ3hDLEdBQUcsSUFBSTtBQUNQLEdBQUcsQ0FBQyxDQUFDO0FBQ0wsRUFBRTtBQUNGLENBQUM7O2lCQXBHTyxHQUFHO0FBQ1gsQ0FBQyxJQUFJLENBQUMsUUFBUSxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsVUFBVSxDQUFDLGdCQUFnQixDQUFDLElBQUksQ0FBQyxHQUFHLEVBQUUsQ0FBQyxLQUFLLENBQUMsQ0FBQztBQUN6RSxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxLQUFLLEVBQUUsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsQ0FBQyxDQUFDOztBQUUzQyxDQUFDLElBQUksQ0FBQyxZQUFZLEVBQUUsQ0FBQztBQUNyQixDQUFDLElBQUksQ0FBQyxZQUFZLEVBQUUsQ0FBQzs7QUFFckIsQ0FBQyxJQUFJLENBQUMsRUFBRSxDQUFDLE9BQU8sRUFBRSxDQUFDLEVBQUUsT0FBTyxFQUFFLEtBQUs7QUFDbkMsRUFBRSxJQUFJLE9BQU8sQ0FBQyxHQUFHLElBQUksT0FBTyxDQUFDLFNBQVMsSUFBSSxPQUFPLENBQUMsTUFBTSxJQUFJLE9BQU8sQ0FBQyxRQUFRLEVBQUU7QUFDOUUsR0FBRyxJQUFJLENBQUMsWUFBWSxFQUFFLENBQUM7QUFDdkIsR0FBRztBQUNILEVBQUUsQ0FBQyxDQUFDOztBQUVKLENBQUMsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsQ0FBQztBQUNuQixDQUFDOztrQkFFUSxHQUFHO0FBQ1osQ0FBQyxPQUFPLENBQUMsTUFBTSxDQUFDLElBQUksQ0FBQyxDQUFDO0FBQ3RCLENBQUM7Ozs7Ozs7Ozs7Ozs7OztZQWxLMkMsY0FBYzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZCQUd4QixLQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzhCQUFMLEtBQUsiLCJmaWxlIjoiZTU5ZDc5OTYxOTU4OTgxZTdiNjQvdmVuZG9yc35fLnZlbmRvcnN+Xy5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzdmVsdGU6d2luZG93IGJpbmQ6aW5uZXJIZWlnaHQ9d2ggb246cmVzaXplPSdoYW5kbGVSZXNpemUoKScvPlxuXG48ZGl2IHJlZjpvdXRlcj5cblx0PGRpdiBjbGFzcz0nYmFja2dyb3VuZC1jb250YWluZXInIHtzdHlsZX0+XG5cdFx0PGRpdiByZWY6YmFja2dyb3VuZD5cblx0XHRcdDxzbG90IG5hbWU9J2JhY2tncm91bmQnPjwvc2xvdD5cblx0XHQ8L2Rpdj5cblx0PC9kaXY+XG5cblx0PGRpdiByZWY6Zm9yZWdyb3VuZD5cblx0XHQ8c2xvdCBuYW1lPSdmb3JlZ3JvdW5kJz48L3Nsb3Q+XG5cdDwvZGl2PlxuPC9kaXY+XG5cbjxzdHlsZT5cblx0cmVmOm91dGVyIHtcblx0XHRwb3NpdGlvbjogcmVsYXRpdmU7XG5cdH1cblxuXHRyZWY6YmFja2dyb3VuZCB7XG5cdFx0cG9zaXRpb246IHJlbGF0aXZlO1xuXHRcdHdpZHRoOiAxMDAlO1xuXHR9XG5cblx0cmVmOmZvcmVncm91bmQge1xuXHRcdHBvc2l0aW9uOiByZWxhdGl2ZTtcblx0XHR6LWluZGV4OiAyO1xuXHR9XG5cblx0cmVmOmZvcmVncm91bmQ6OmFmdGVyIHtcblx0XHRjb250ZW50OiAnICc7XG5cdFx0ZGlzcGxheTogYmxvY2s7XG5cdFx0Y2xlYXI6IGJvdGg7XG5cdH1cblxuXHQuYmFja2dyb3VuZC1jb250YWluZXIge1xuXHRcdHBvc2l0aW9uOiBhYnNvbHV0ZTtcblx0XHR3aWR0aDogMTAwJTtcblx0XHRwb2ludGVyLWV2ZW50czogbm9uZTtcblx0XHQvKiBoZWlnaHQ6IDEwMCU7ICovXG5cblx0XHQvKiBpbiB0aGVvcnkgdGhpcyBoZWxwcyBwcmV2ZW50IGp1bXBpbmcgKi9cblx0XHR3aWxsLWNoYW5nZTogdHJhbnNmb3JtO1xuXHRcdC8qIC13ZWJraXQtdHJhbnNmb3JtOiB0cmFuc2xhdGUzZCgwLCAwLCAwKTtcblx0XHQtbW96LXRyYW5zZm9ybTogdHJhbnNsYXRlM2QoMCwgMCwgMCk7XG5cdFx0dHJhbnNmb3JtOiB0cmFuc2xhdGUzZCgwLCAwLCAwKTsgKi9cblx0fVxuPC9zdHlsZT5cblxuPHNjcmlwdD5cblx0Y29uc3Qgc2Nyb2xsZXJzID0gW107XG5cblx0aWYgKHR5cGVvZiB3aW5kb3cgIT09ICd1bmRlZmluZWQnKSB7XG5cdFx0d2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ3Njcm9sbCcsICgpID0+IHtcblx0XHRcdHNjcm9sbGVycy5mb3JFYWNoKHNjcm9sbGVyID0+IHtcblx0XHRcdFx0c2Nyb2xsZXIuaGFuZGxlU2Nyb2xsKCk7XG5cdFx0XHR9KTtcblx0XHR9KTtcblx0fVxuXG5cdGxldCBtYW5hZ2VyO1xuXG5cdGlmICh0eXBlb2YgSW50ZXJzZWN0aW9uT2JzZXJ2ZXIgIT09ICd1bmRlZmluZWQnKSB7XG5cdFx0Y29uc3QgbWFwID0gbmV3IE1hcCgpO1xuXG5cdFx0Y29uc3Qgb2JzZXJ2ZXIgPSBuZXcgSW50ZXJzZWN0aW9uT2JzZXJ2ZXIoKGVudHJpZXMsIG9ic2VydmVyKSA9PiB7XG5cdFx0XHRlbnRyaWVzLmZvckVhY2goZW50cnkgPT4ge1xuXHRcdFx0XHRjb25zdCBzY3JvbGxlciA9IG1hcC5nZXQoZW50cnkudGFyZ2V0KTtcblx0XHRcdFx0Y29uc3QgaW5kZXggPSBzY3JvbGxlcnMuaW5kZXhPZihzY3JvbGxlcik7XG5cblx0XHRcdFx0aWYgKGVudHJ5LmlzSW50ZXJzZWN0aW5nKSB7XG5cdFx0XHRcdFx0aWYgKGluZGV4ID09PSAtMSkgc2Nyb2xsZXJzLnB1c2goc2Nyb2xsZXIpO1xuXHRcdFx0XHR9IGVsc2Uge1xuXHRcdFx0XHRcdGlmIChpbmRleCAhPT0gLTEpIHNjcm9sbGVycy5zcGxpY2UoaW5kZXgsIDEpO1xuXHRcdFx0XHR9XG5cdFx0XHR9KTtcblx0XHR9LCB7XG5cdFx0XHRyb290TWFyZ2luOiAnNDAwcHggMHB4J1xuXHRcdH0pO1xuXG5cdFx0bWFuYWdlciA9IHtcblx0XHRcdGFkZDogc2Nyb2xsZXIgPT4ge1xuXHRcdFx0XHRjb25zdCB7IG91dGVyIH0gPSBzY3JvbGxlci5yZWZzO1xuXHRcdFx0XHRjb25zdCB7IHRvcCwgYm90dG9tIH0gPSBvdXRlci5nZXRCb3VuZGluZ0NsaWVudFJlY3QoKTtcblxuXHRcdFx0XHRpZiAodG9wIDwgd2luZG93LmlubmVySGVpZ2h0ICYmIGJvdHRvbSA+IDApIHNjcm9sbGVycy5wdXNoKHNjcm9sbGVyKTtcblxuXHRcdFx0XHRtYXAuc2V0KG91dGVyLCBzY3JvbGxlcik7XG5cdFx0XHRcdG9ic2VydmVyLm9ic2VydmUob3V0ZXIpO1xuXHRcdFx0fSxcblxuXHRcdFx0cmVtb3ZlOiBzY3JvbGxlciA9PiB7XG5cdFx0XHRcdGNvbnN0IGluZGV4ID0gc2Nyb2xsZXJzLmluZGV4T2Yoc2Nyb2xsZXIpO1xuXHRcdFx0XHRpZiAoaW5kZXggIT09IC0xKSBzY3JvbGxlcnMuc3BsaWNlKGluZGV4LCAxKTtcblxuXHRcdFx0XHRtYXAuZGVsZXRlKHNjcm9sbGVyLnJlZnMub3V0ZXIpO1xuXHRcdFx0XHRvYnNlcnZlci51bm9ic2VydmUoc2Nyb2xsZXIucmVmcy5vdXRlcik7XG5cdFx0XHR9XG5cdFx0fTtcblx0fSBlbHNlIHtcblx0XHRtYW5hZ2VyID0ge1xuXHRcdFx0YWRkOiBzY3JvbGxlciA9PiB7XG5cdFx0XHRcdHNjcm9sbGVycy5wdXNoKHNjcm9sbGVyKTtcblx0XHRcdH0sXG5cblx0XHRcdHJlbW92ZTogc2Nyb2xsZXIgPT4ge1xuXHRcdFx0XHRjb25zdCBpbmRleCA9IHNjcm9sbGVycy5pbmRleE9mKHNjcm9sbGVyKTtcblx0XHRcdFx0aWYgKGluZGV4ICE9PSAtMSkgc2Nyb2xsZXJzLnNwbGljZShpbmRleCwgMSk7XG5cdFx0XHR9XG5cdFx0fTtcblx0fVxuXG5cdGV4cG9ydCBkZWZhdWx0IHtcblx0XHRkYXRhKCkge1xuXHRcdFx0cmV0dXJuIHtcblx0XHRcdFx0dG9wOiAwLFxuXHRcdFx0XHRib3R0b206IDEsXG5cdFx0XHRcdHRocmVzaG9sZDogMC41LFxuXG5cdFx0XHRcdGNvdW50OiAwLFxuXHRcdFx0XHRpbmRleDogMCxcblx0XHRcdFx0b2Zmc2V0OiAwLFxuXHRcdFx0XHRwcm9ncmVzczogMCxcblxuXHRcdFx0XHRxdWVyeTogJ3NlY3Rpb24nXG5cdFx0XHR9O1xuXHRcdH0sXG5cblx0XHRjb21wdXRlZDoge1xuXHRcdFx0dG9wX3B4OiAoeyB0b3AsIHdoIH0pID0+IE1hdGgucm91bmQodG9wICogd2gpLFxuXHRcdFx0Ym90dG9tX3B4OiAoeyBib3R0b20sIHdoIH0pID0+IE1hdGgucm91bmQoYm90dG9tICogd2gpLFxuXHRcdFx0dGhyZXNob2xkX3B4OiAoeyB0aHJlc2hvbGQsIHdoIH0pID0+IE1hdGgucm91bmQodGhyZXNob2xkICogd2gpLFxuXG5cdFx0XHRzdHlsZSh7IGZpeGVkLCBvZmZzZXRfdG9wLCBib3R0b21fcHgsIHRvcF9weCwgd2lkdGgsIGhlaWdodCwgaW52ZXJ0ZWQgfSkge1xuXHRcdFx0XHRyZXR1cm4gYFxuXHRcdFx0XHRcdHBvc2l0aW9uOiAke2ZpeGVkID8gJ2ZpeGVkJyA6ICdhYnNvbHV0ZSd9O1xuXHRcdFx0XHRcdHRvcDogMDtcblx0XHRcdFx0XHR0cmFuc2Zvcm06IHRyYW5zbGF0ZSgwLCAke29mZnNldF90b3B9cHgpO1xuXHRcdFx0XHRcdHdpZHRoOiAke3dpZHRofXB4O1xuXHRcdFx0XHRcdHotaW5kZXg6ICR7aW52ZXJ0ZWQgPyAzIDogMX07XG5cdFx0XHRcdGA7XG5cdFx0XHR9XG5cdFx0fSxcblxuXHRcdG9uY3JlYXRlKCkge1xuXHRcdFx0dGhpcy5zZWN0aW9ucyA9IHRoaXMucmVmcy5mb3JlZ3JvdW5kLnF1ZXJ5U2VsZWN0b3JBbGwodGhpcy5nZXQoKS5xdWVyeSk7XG5cdFx0XHR0aGlzLnNldCh7IGNvdW50OiB0aGlzLnNlY3Rpb25zLmxlbmd0aCB9KTtcblxuXHRcdFx0dGhpcy5oYW5kbGVSZXNpemUoKTtcblx0XHRcdHRoaXMuaGFuZGxlU2Nyb2xsKCk7XG5cblx0XHRcdHRoaXMub24oJ3N0YXRlJywgKHsgY2hhbmdlZCB9KSA9PiB7XG5cdFx0XHRcdGlmIChjaGFuZ2VkLnRvcCB8fCBjaGFuZ2VkLnRocmVzaG9sZCB8fCBjaGFuZ2VkLmJvdHRvbSB8fCBjaGFuZ2VkLnBhcmFsbGF4KSB7XG5cdFx0XHRcdFx0dGhpcy5oYW5kbGVTY3JvbGwoKTtcblx0XHRcdFx0fVxuXHRcdFx0fSk7XG5cblx0XHRcdG1hbmFnZXIuYWRkKHRoaXMpO1xuXHRcdH0sXG5cblx0XHRvbmRlc3Ryb3koKSB7XG5cdFx0XHRtYW5hZ2VyLnJlbW92ZSh0aGlzKTtcblx0XHR9LFxuXG5cdFx0bWV0aG9kczoge1xuXHRcdFx0aGFuZGxlU2Nyb2xsKCkge1xuXHRcdFx0XHRjb25zdCB7IHRvcF9weCwgYm90dG9tX3B4LCB0aHJlc2hvbGRfcHgsIHBhcmFsbGF4IH0gPSB0aGlzLmdldCgpO1xuXG5cdFx0XHRcdC8vIGRldGVybWluZSBmaXggc3RhdGVcblx0XHRcdFx0Y29uc3QgZm9yZWdyb3VuZCA9IHRoaXMucmVmcy5mb3JlZ3JvdW5kLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuXHRcdFx0XHRjb25zdCBiYWNrZ3JvdW5kID0gdGhpcy5yZWZzLmJhY2tncm91bmQuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7XG5cblx0XHRcdFx0Ly8gb25seSB1cGRhdGUgd2hpbGUgdGhlIGZvcmVncm91bmQgaXMgdmlzaWJsZVxuXHRcdFx0XHQvLyAob25seSBhZmZlY3RzIGJyb3dzZXJzIHdpdGhvdXQgSW50ZXJzZWN0aW9uT2JzZXJ2ZXIpXG5cdFx0XHRcdGlmIChmb3JlZ3JvdW5kLnRvcCA+IHdpbmRvdy5pbm5lckhlaWdodCB8fCBmb3JlZ3JvdW5kLmJvdHRvbSA8IDApIHJldHVybjtcblxuXHRcdFx0XHRjb25zdCBmb3JlZ3JvdW5kX2hlaWdodCA9IGZvcmVncm91bmQuYm90dG9tIC0gZm9yZWdyb3VuZC50b3A7XG5cdFx0XHRcdGNvbnN0IGJhY2tncm91bmRfaGVpZ2h0ID0gYmFja2dyb3VuZC5ib3R0b20gLSBiYWNrZ3JvdW5kLnRvcDtcblxuXHRcdFx0XHRjb25zdCBhdmFpbGFibGVfc3BhY2UgPSBib3R0b21fcHggLSB0b3BfcHg7XG5cdFx0XHRcdGNvbnN0IHAgPSAodG9wX3B4IC0gZm9yZWdyb3VuZC50b3ApIC8gKGZvcmVncm91bmRfaGVpZ2h0IC0gYXZhaWxhYmxlX3NwYWNlKTtcblxuXHRcdFx0XHRjb25zdCB7IHNlY3Rpb25zIH0gPSB0aGlzO1xuXG5cdFx0XHRcdGxldCBvZmZzZXRfdG9wO1xuXHRcdFx0XHRsZXQgZml4ZWQ7XG5cdFx0XHRcdGxldCBpbmRleDtcblx0XHRcdFx0bGV0IG9mZnNldDtcblxuXHRcdFx0XHRpZiAocCA8PSAwKSB7XG5cdFx0XHRcdFx0b2Zmc2V0X3RvcCA9IDA7XG5cdFx0XHRcdFx0Zml4ZWQgPSBmYWxzZTtcblx0XHRcdFx0XHRvZmZzZXQgPSAwO1xuXHRcdFx0XHRcdGluZGV4ID0gLTE7XG5cdFx0XHRcdH0gZWxzZSBpZiAocCA+PSAxKSB7XG5cdFx0XHRcdFx0b2Zmc2V0X3RvcCA9IHBhcmFsbGF4XG5cdFx0XHRcdFx0XHQ/IChmb3JlZ3JvdW5kX2hlaWdodCAtIGJhY2tncm91bmRfaGVpZ2h0KVxuXHRcdFx0XHRcdFx0OiAoZm9yZWdyb3VuZF9oZWlnaHQgLSBhdmFpbGFibGVfc3BhY2UpO1xuXHRcdFx0XHRcdGZpeGVkID0gZmFsc2U7XG5cdFx0XHRcdFx0b2Zmc2V0ID0gMTtcblx0XHRcdFx0XHRpbmRleCA9IHNlY3Rpb25zLmxlbmd0aCAtIDE7XG5cdFx0XHRcdH0gZWxzZSB7XG5cdFx0XHRcdFx0b2Zmc2V0X3RvcCA9IHBhcmFsbGF4ID9cblx0XHRcdFx0XHRcdE1hdGgucm91bmQodG9wX3B4IC0gcCAqIChiYWNrZ3JvdW5kX2hlaWdodCAtIGF2YWlsYWJsZV9zcGFjZSkpIDpcblx0XHRcdFx0XHRcdHRvcF9weDtcblx0XHRcdFx0XHRmaXhlZCA9IHRydWU7XG5cdFx0XHRcdH1cblxuXHRcdFx0XHRmb3IgKGluZGV4ID0gMDsgaW5kZXggPCB0aGlzLnNlY3Rpb25zLmxlbmd0aDsgaW5kZXggKz0gMSkge1xuXHRcdFx0XHRcdGNvbnN0IHNlY3Rpb24gPSB0aGlzLnNlY3Rpb25zW2luZGV4XTtcblx0XHRcdFx0XHRjb25zdCB7IHRvcCB9ID0gc2VjdGlvbi5nZXRCb3VuZGluZ0NsaWVudFJlY3QoKTtcblxuXHRcdFx0XHRcdGNvbnN0IG5leHQgPSB0aGlzLnNlY3Rpb25zW2luZGV4ICsgMV07XG5cdFx0XHRcdFx0Y29uc3QgYm90dG9tID0gbmV4dCA/IG5leHQuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCkudG9wIDogdGhpcy5yZWZzLmZvcmVncm91bmQuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCkuYm90dG9tO1xuXG5cdFx0XHRcdFx0aWYgKGJvdHRvbSA+PSB0aHJlc2hvbGRfcHgpIHtcblx0XHRcdFx0XHRcdG9mZnNldCA9ICh0aHJlc2hvbGRfcHggLSB0b3ApIC8gKGJvdHRvbSAtIHRvcCk7XG5cdFx0XHRcdFx0XHRicmVhaztcblx0XHRcdFx0XHR9XG5cdFx0XHRcdH1cblxuXHRcdFx0XHR0aGlzLnNldCh7XG5cdFx0XHRcdFx0cHJvZ3Jlc3M6IHAsXG5cdFx0XHRcdFx0aW5kZXgsXG5cdFx0XHRcdFx0b2Zmc2V0LFxuXG5cdFx0XHRcdFx0b2Zmc2V0X3RvcCxcblx0XHRcdFx0XHRmaXhlZFxuXHRcdFx0XHR9KTtcblx0XHRcdH0sXG5cblx0XHRcdGhhbmRsZVJlc2l6ZSgpIHtcblx0XHRcdFx0Y29uc3QgeyBsZWZ0LCByaWdodCB9ID0gdGhpcy5yZWZzLm91dGVyLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuXG5cdFx0XHRcdGNvbnN0IGJnID0gdGhpcy5yZWZzLmJhY2tncm91bmQuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7XG5cdFx0XHRcdGNvbnN0IGZnID0gdGhpcy5yZWZzLmZvcmVncm91bmQuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7XG5cblx0XHRcdFx0dGhpcy5zZXQoe1xuXHRcdFx0XHRcdHdpZHRoOiByaWdodCAtIGxlZnQsXG5cdFx0XHRcdFx0Zm9yZWdyb3VuZF9oZWlnaHQ6IGZnLmJvdHRvbSAtIGZnLnRvcCxcblx0XHRcdFx0XHRiYWNrZ3JvdW5kX2hlaWdodDogYmcuYm90dG9tIC0gYmcudG9wLFxuXHRcdFx0XHRcdGxlZnRcblx0XHRcdFx0fSk7XG5cdFx0XHR9XG5cdFx0fVxuXHR9O1xuPC9zY3JpcHQ+XG4iXSwic291cmNlUm9vdCI6IiJ9