/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./app/service-worker.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./app/manifest/service-worker.js":
/*!****************************************!*\
  !*** ./app/manifest/service-worker.js ***!
  \****************************************/
/*! exports provided: timestamp, assets, shell, routes */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"timestamp\", function() { return timestamp; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"assets\", function() { return assets; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"shell\", function() { return shell; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"routes\", function() { return routes; });\n// This file is generated by Sapper — do not edit it!\nconst timestamp = 1529300806644;\n\nconst assets = [\n\t\"belmu.css\",\n\t\"belmu.out.css\",\n\t\"belmu/_base/_defaults/_base.colours.css\",\n\t\"belmu/_base/_defaults/_base.fix.css\",\n\t\"belmu/_base/_defaults/_base.fonts.css\",\n\t\"belmu/_base/_defaults/_base.forms.css\",\n\t\"belmu/_base/_defaults/_base.typography.css\",\n\t\"belmu/_base/_defaults/_base.vars.css\",\n\t\"belmu/_element/_defaults/_element.icons.css\",\n\t\"belmu/_element/_defaults/_element.triangles.css\",\n\t\"belmu/_layout/_defaults/_layout.flex.css\",\n\t\"belmu/_layout/_defaults/_layout.grid.css\",\n\t\"belmu/_layout/_defaults/_layout.masonry.css\",\n\t\"belmu/_module/_defaults/_module.intro.css\",\n\t\"belmu/_utility/_defaults/_utility.colours.css\",\n\t\"belmu/_utility/_defaults/_utility.display.css\",\n\t\"belmu/_utility/_defaults/_utility.floats.css\",\n\t\"belmu/_utility/_defaults/_utility.percentages.css\",\n\t\"belmu/_utility/_defaults/_utility.positioning.css\",\n\t\"belmu/_utility/_defaults/_utility.shame.css\",\n\t\"belmu/_utility/_defaults/_utility.spacing.css\",\n\t\"belmu/_utility/_defaults/_utility.text.css\",\n\t\"belmu/_utility/_defaults/_utility.typesizes.css\",\n\t\"global.css\",\n\t\"manifest.json\"\n];\n\nconst shell = [\n\t\"client/7617d7eb457232145945/_._.js\",\n\t\"client/7617d7eb457232145945/main.js\",\n\t\"client/7617d7eb457232145945/0.0.js\",\n\t\"client/7617d7eb457232145945/vendors~_.vendors~_.js\"\n];\n\nconst routes = [\n\t\n];\n\n//# sourceURL=webpack:///./app/manifest/service-worker.js?");

/***/ }),

/***/ "./app/service-worker.js":
/*!*******************************!*\
  !*** ./app/service-worker.js ***!
  \*******************************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./manifest/service-worker.js */ \"./app/manifest/service-worker.js\");\n\n\nconst ASSETS = `cache${_manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`;\n\n// `shell` is an array of all the files generated by webpack,\n// `assets` is an array of everything in the `assets` directory\nconst to_cache = _manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"shell\"].concat(_manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"assets\"]);\nconst cached = new Set(to_cache);\n\nself.addEventListener('install', event => {\n\tevent.waitUntil(\n\t\tcaches\n\t\t\t.open(ASSETS)\n\t\t\t.then(cache => cache.addAll(to_cache))\n\t\t\t.then(() => {\n\t\t\t\tself.skipWaiting();\n\t\t\t})\n\t);\n});\n\nself.addEventListener('activate', event => {\n\tevent.waitUntil(\n\t\tcaches.keys().then(async keys => {\n\t\t\t// delete old caches\n\t\t\tfor (const key of keys) {\n\t\t\t\tif (key !== ASSETS) await caches.delete(key);\n\t\t\t}\n\n\t\t\tself.clients.claim();\n\t\t})\n\t);\n});\n\nself.addEventListener('fetch', event => {\n\tif (event.request.method !== 'GET') return;\n\n\tconst url = new URL(event.request.url);\n\n\t// don't try to handle e.g. data: URIs\n\tif (!url.protocol.startsWith('http')) return;\n\n\t// ignore dev server requests\n\tif (url.hostname === self.location.hostname && url.port !== self.location.port) return;\n\n\t// always serve assets and webpack-generated files from cache\n\tif (url.host === self.location.host && cached.has(url.pathname)) {\n\t\tevent.respondWith(caches.match(event.request));\n\t\treturn;\n\t}\n\n\t// for pages, you might want to serve a shell `index.html` file,\n\t// which Sapper has generated for you. It's not right for every\n\t// app, but if it's right for yours then uncomment this section\n\t/*\n\tif (url.origin === self.origin && routes.find(route => route.pattern.test(url.pathname))) {\n\t\tevent.respondWith(caches.match('/index.html'));\n\t\treturn;\n\t}\n\t*/\n\n\t// for everything else, try the network first, falling back to\n\t// cache if the user is offline. (If the pages never change, you\n\t// might prefer a cache-first approach to a network-first one.)\n\tevent.respondWith(\n\t\tcaches\n\t\t\t.open(`offline${_manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`)\n\t\t\t.then(async cache => {\n\t\t\t\ttry {\n\t\t\t\t\tif (event.request.cache === 'only-if-cache') {\n\t\t\t\t\t\t// workaround Chrome devtools bug https://github.com/sveltejs/sapper-template/issues/34\n\t\t\t\t\t\tevent.request.mode = 'same-origin';\n\t\t\t\t\t}\n\n\t\t\t\t\tconst response = await fetch(event.request);\n\t\t\t\t\tcache.put(event.request, response.clone());\n\t\t\t\t\treturn response;\n\t\t\t\t} catch(err) {\n\t\t\t\t\tconst response = await cache.match(event.request);\n\t\t\t\t\tif (response) return response;\n\n\t\t\t\t\tthrow err;\n\t\t\t\t}\n\t\t\t})\n\t);\n});\n\n\n//# sourceURL=webpack:///./app/service-worker.js?");

/***/ })

/******/ });