// This file is generated by Sapper — do not edit it!
export const routes = [
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ pattern: /^\/style\/?$/, ignore: true }
];

if (module.hot) {
	import('/Users/me/Sites/OLD_Sites/belmu/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}