// This file is generated by Sapper — do not edit it!
export const routes = [
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ pattern: /^\/style\/?$/, ignore: true }
];