// This file is generated by Sapper — do not edit it!
import _0 from '../../routes/index.html';
import * as style0 from '../../routes/style.css';

export const routes = [
	{ id: '_', pattern: /^\/?$/, params: () => ({}), handlers: [{ type: 'page', module: _0 }] },
	{ id: 'style', pattern: /^\/style\/?$/, params: () => ({}), handlers: [{ type: 'route', module: style0 }] }
];