// This file is generated by Sapper — do not edit it!
export const timestamp = 1529925915918;

export const assets = [
	"belmu-svg.svg",
	"belmu.css",
	"belmu.out.css",
	"belmu/_base/_base.colours.css",
	"belmu/_base/_base.fix.css",
	"belmu/_base/_base.fonts.css",
	"belmu/_base/_base.forms.css",
	"belmu/_base/_base.typography.css",
	"belmu/_base/_base.vars.css",
	"belmu/_element/_element.icons.css",
	"belmu/_element/_element.triangles.css",
	"belmu/_layout/_layout.intro.css",
	"belmu/_module/_module.intro.css",
	"belmu/_utility/_utility.colours.css",
	"belmu/_utility/_utility.display.css",
	"belmu/_utility/_utility.floats.css",
	"belmu/_utility/_utility.layout.flex.css",
	"belmu/_utility/_utility.layout.grid.css",
	"belmu/_utility/_utility.layout.masonry.css",
	"belmu/_utility/_utility.percentages.css",
	"belmu/_utility/_utility.positioning.css",
	"belmu/_utility/_utility.shame.css",
	"belmu/_utility/_utility.spacing.css",
	"belmu/_utility/_utility.text.css",
	"belmu/_utility/_utility.typesizes.css",
	"global.css",
	"manifest.json",
	"svg/symbols.svg",
	"symbols.html"
];

export const shell = [
	"client/52b0ab5413ca54f472d7/_._.js",
	"client/52b0ab5413ca54f472d7/main.js",
	"client/52b0ab5413ca54f472d7/0.0.js",
	"client/52b0ab5413ca54f472d7/vendors~_.vendors~_.js",
	"client/sprite.svg"
];

export const routes = [
	
];